// Action for getting top headlines
export const GET_TOP_HEADLINES = 'GET_TOP_HEADLINES';
export const GET_TOP_HEADLINES_SUCCESS = 'GET_TOP_HEADLINES_SUCCESS';
export const GET_TOP_HEADLINES_FAIL = 'GET_TOP_HEADLINES_FAIL';

export const GET_MORE_TOP_HEADLINES = 'GET_MORE_TOP_HEADLINES';
export const GET_MORE_TOP_HEADLINES_SUCCESS = 'GET_MORE_TOP_HEADLINES_SUCCESS';
export const GET_MORE_TOP_HEADLINES_FAIL = 'GET_MORE_TOP_HEADLINES_FAIL';

// Actions for getting top headlines by category
export const GET_BUSINESS_HEADLINES = 'GET_BUSINESS_HEADLINES';
export const GET_BUSINESS_HEADLINES_SUCCESS = 'GET_BUSINESS_HEADLINES_SUCCESS';
export const GET_BUSINESS_HEADLINES_FAIL = 'GET_BUSINESS_HEADLINES_FAIL';

export const GET_ENTERTAINMENT_HEADLINES = 'GET_ENTERTAINMENT_HEADLINES';
export const GET_ENTERTAINMENT_HEADLINES_SUCCESS = 'GET_ENTERTAINMENT_HEADLINES_SUCCESS';
export const GET_ENTERTAINMENT_HEADLINES_FAIL = 'GET_ENTERTAINMENT_HEADLINES_FAIL';

export const GET_GENERAL_HEADLINES = 'GET_GENERAL_HEADLINES';
export const GET_GENERAL_HEADLINES_SUCCESS = 'GET_GENERAL_HEADLINES_SUCCESS';
export const GET_GENERAL_HEADLINES_FAIL = 'GET_GENERAL_HEADLINES_FAIL';

export const GET_HEALTH_HEADLINES = 'GET_HEALTH_HEADLINES';
export const GET_HEALTH_HEADLINES_SUCCESS = 'GET_HEALTH_HEADLINES_SUCCESS';
export const GET_HEALTH_HEADLINES_FAIL = 'GET_HEALTH_HEADLINES_FAIL';

export const GET_SCIENCE_HEADLINES = 'GET_SCIENCE_HEADLINES';
export const GET_SCIENCE_HEADLINES_SUCCESS = 'GET_SCIENCE_HEADLINES_SUCCESS';
export const GET_SCIENCE_HEADLINES_FAIL = 'GET_SCIENCE_HEADLINES_FAIL';

export const GET_SPORTS_HEADLINES = 'GET_SPORTS_HEADLINES';
export const GET_SPORTS_HEADLINES_SUCCESS = 'GET_SPORTS_HEADLINES_SUCCESS';
export const GET_SPORTS_HEADLINES_FAIL = 'GET_SPORTS_HEADLINES_FAIL';

export const GET_TECHNOLOGY_HEADLINES = 'GET_TECHNOLOGY_HEADLINES';
export const GET_TECHNOLOGY_HEADLINES_SUCCESS = 'GET_TECHNOLOGY_HEADLINES_SUCCESS';
export const GET_TECHNOLOGY_HEADLINES_FAIL = 'GET_TECHNOLOGY_HEADLINES_FAIL';
